
export const LIST_REQUEST = {
  FETCH_ALL_REQUEST: 'FETCH_ALL_REQUEST',
  FETCH_ALL_REQUEST_SUCCESS: 'FETCH_ALL_REQUEST_SUCCESS',
  FETCH_ALL_REQUEST_FAILED: 'FETCH_ALL_REQUEST_FAILED',
  FETCH_FILTER_OPTIONS: 'FETCH_FILTER_OPTIONS',
  FETCH_FILTER_OPTIONS_SUCCESS: 'FETCH_FILTER_OPTIONS_SUCCESS',
  FETCH_FILTER_OPTIONS_FAILED: 'FETCH_FILTER_OPTIONS_FAILED',
  FETCH_HANDLE_FILTER: 'FETCH_HANDLE_FILTER',
  FETCH_HANDLE_CHANGE_PAGE: 'FETCH_HANDLE_CHANGE_PAGE'
}

export const HISTORY_REQUEST = {
  FETCH_ALL_HISTORY_REQUEST: 'FETCH_ALL_HISTORY_REQUEST',
  FETCH_ALL_HISTORY_REQUEST_SUCCESS: 'FETCH_ALL_HISTORY_REQUEST_SUCCESS',
  FETCH_ALL_HISTORY_REQUEST_FAILED: 'FETCH_ALL_HISTORY_REQUEST_FAILED',
  FETCH_HANDLE_CHANGE_PAGE_HISTORY: 'FETCH_HANDLE_CHANGE_PAGE_HISTORY'
}

export const LOGIN = {
  HANDLE_LOGIN: 'HANDLE_LOGIN',
  HANDLE_LOGIN_WITH_GOOGLE: 'HANDLE_LOGIN_WITH_GOOGLE',
  HANDLE_LOGIN_SUCCESS: 'HANDLE_LOGIN_SUCCESS',
  HANDLE_LOGIN_FAILED: 'HANDLE_LOGIN_FAILED'
}

export const UI = {
  HANDLE_SHOW_TOAST: 'HANDLE_SHOW_TOAST',
  HANDLE_HIDE_TOAST: 'HANDLE_HIDE_TOAST',
  HANLDE_SHOW_OR_HIDE_SIDEBAR: 'HANLDE_SHOW_OR_HIDE_SIDEBAR',
}
export const REQUEST = {
  FETCH_REQUEST_DETAIL: 'FETCH_REQUEST_DETAIL',
  FETCH_REQUEST_DETAIL_SUCCESS: 'FETCH_REQUEST_DETAIL_SUCCESS',
  FETCH_REQUEST_DETAIL_FAILED: 'FETCH_REQUEST_DETAIL_FAILED',
  FETCH_ADMIN_REQUEST: 'FETCH_ADMIN_REQUEST',
  FETCH_ADMIN_REQUEST_SUCCESS: 'FETCH_ADMIN_REQUEST_SUCCESS',
  FETCH_DELETE_REQUEST: 'FETCH_DELETE_REQUEST',
  FETCH_APPROVE_REQUEST: 'FETCH_APPROVE_REQUEST',
  FETCH_REJECT_REQUEST: 'FETCH_REJECT_REQUEST',
  FETCH_UPDATE_REQUEST_BY_ADMIN: 'FETCH_UPDATE_REQUEST_BY_ADMIN'
}

export const OPTION = {
  FETCH_ALL_STATUS: 'FETCH_ALL_STATUS',
  FETCH_ALL_STATUS_SUCCESS: 'FETCH_ALL_STATUS_SUCCESS',
  FETCH_ALL_CATEGORY: 'FETCH_ALL_CATEGORY',
  FETCH_ALL_CATEGORY_SUCCESS: 'FETCH_ALL_CATEGORY_SUCCESS',
  FETCH_ALL_ADMIN: 'FETCH_ALL_ADMIN',
  FETCH_ALL_ADMIN_SUCCESS: 'FETCH_ALL_ADMIN_SUCCESS',
  FETCH_ALL_PRIORITY: 'FETCH_ALL_PRIORITY',
  FETCH_ALL_PRIORITY_SUCCESS: 'FETCH_ALL_PRIORITY_SUCCESS',
  FETCH_ALL_USER: 'FETCH_ALL_USER',
  FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
  FETCH_CATEGORY_AFTER_CHANGE_ASSIGN: 'FETCH_CATEGORY_AFTER_CHANGE_ASSIGN',
  FETCH_ASSGIN_AFTER_CHANGE_CATEGORY: 'FETCH_ASSGIN_AFTER_CHANGE_CATEGORY',
  FETCH_ALL_DEPARTMENT: 'FETCH_ALL_DEPARTMENT',
  FETCH_ALL_DEPARTMENT_SUCCESS: 'FETCH_ALL_DEPARTMENT_SUCCESS'
}

export const ME = {
  GET_ME: 'GET_ME',
  GET_ME_SUCCESS: 'GET_ME_SUCCESS'
}

export const ACTION_REQUEST = {
  ADD_NEW_REQUEST: 'ADD_NEW_REQUEST',
  ADD_NEW_REQUEST_SUCCESS: 'ADD_NEW_REQUEST_SUCCESS',
  UPDATE_REQUEST: 'UPDATE_REQUEST',
}

export const LOGOUT = {
  FETCH_LOGOUT: 'FETCH_LOGOUT'
}

export const FORGOT = {
  FETCH_FORGOT_PASSWORD: 'FETCH_FORGOT_PASSWORD'
}

export const RESET = {
  FETCH_RESET_PASSWORD: 'FETCH_RESET_PASSWORD'
}

export const CATEGORY = {
  FETCH_ALL_CATE: 'FETCH_ALL_CATE',
  FETCH_ALL_CATE_SUCCESS: 'FETCH_ALL_CATE_SUCCESS',
  FETCH_ADD_CATEGORY: 'FETCH_ADD_CATEGORY',
  FETCH_UPDATE_CATE: 'FETCH_UPDATE_CATE',
}

export const USER = {
  FETCH_ALL_USERS: 'FETCH_ALL_USERS',
  FETCH_ALL_USERS_SUCCESS:'FETCH_ALL_USERS_SUCCESS',
  FETCH_ADD_USER: 'FETCH_ADD_USER',
  FETCH_UPDATE_USER:'FETCH_UPDATE_USER',
  FETCH_HANDLE_CHANGE_PAGE_USER: 'FETCH_HANDLE_CHANGE_PAGE_USER',
  FETCH_SEARCH_USER_BY_NAME: 'FETCH_SEARCH_USER_BY_NAME',
  FETCH_CHANGE_STATUS: 'FETCH_CHANGE_STATUS'
}
export const COMMENT = {
  FETCH_ALL_COMMENT: 'FETCH_ALL_COMMENT',
  FETCH_ALL_COMMENT_SUCCESS: 'FETCH_ALL_COMMENT_SUCCESS',
  FETCH_ALL_COMMENT_FAILED: 'FETCH_ALL_COMMENT_FAILED'
}

export const ACTION_COMMENT = {
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS'
}

export const MY_REQUEST = {
  FETCH_ALL_MY_REQUEST: 'FETCH_ALL_MY_REQUEST',
  FETCH_ALL_MY_REQUEST_SUCCESS: 'FETCH_ALL_MY_REQUEST_SUCCESS',
  FETCH_ALL_MY_REQUEST_FAILED: 'FETCH_ALL_MY_REQUEST_FAILED'
}

export const DEPARTMENT_REQUEST = {
  FETCH_ALL_DEPARTMENT_REQUEST: 'FETCH_ALL_DEPARTMENT_REQUEST',
  FETCH_ALL_DEPARTMENT_REQUEST_SUCCESS: 'FETCH_ALL_DEPARTMENT_REQUEST_SUCCESS',
  FETCH_ALL_DEPARTMENT_REQUEST_FAILED: 'FETCH_ALL_DEPARTMENT_REQUEST_FAILED'
}

export const DEPARTMENT = {
  FETCH_ALL_DEPT: 'FETCH_ALL_DEPT',
  FETCH_ALL_DEPT_SUCCESS: 'FETCH_ALL_DEPT_SUCCESS',
  FETCH_ADD_DEPARTMENT: 'FETCH_ADD_DEPARTMENT',
  FETCH_UPDATE_DEPT: 'FETCH_UPDATE_DEPT'
}
